# conda env create --name eniac -f .\conda-environment.yaml

name: eniac
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - ipywidgets
  - joblib
  - jupyterlab
  - lightgbm==3.0.0
  - matplotlib
  - nodejs
  - pandas==1.1.3
  - pip
  - pyaml
  - scikit-learn==0.23.2
  - scikit-optimize==0.8.1
  - scipy
  - sqlalchemy
  - seaborn
  - tqdm
  - pip:
    - pyarrow
    - xgboost==1.2.1
















